/**
 * Stub for iconv-lite on Cloudflare Workers. Generated by the ExpressoTS CLI.
 * Express body parsing is disabled on this target, so these APIs must never run.
 */
const UNSUPPORTED =
  "iconv-lite is not available on Cloudflare Workers. Read parsed data from req.body instead.";

function unsupported() {
  throw new Error(UNSUPPORTED);
}

module.exports = {
  encodingExists: unsupported,
  decode: unsupported,
  encode: unsupported,
  getDecoder: unsupported,
  getEncoder: unsupported,
};
